### ISSUE TITLE
Library tab stuck in Analysing Your Library

### ISSUE THREAD

**Issue by tegraion** [harbassan/spicetify-stats#2] opened 2023-05-03 17:34 UTC
![image](https://user-images.githubusercontent.com/119058830/235996875-19d67b07-d44d-4179-ab42-89fb305191f6.png)

Other tabs works properly. Library tab doesn't show anything.

Installed the app as directed in the readme.md

Spotify for Windows
1.2.10.760.g52970952
Spicetify v2.17.2
Theme: Nord / Nord
Extensions: popupLyrics.js, bookmark.js, listPlaylistsWithSong.js, playlistIntersection.js, spotifyGenres.js, romaja_lyrics.js, romaji_lyrics.js, fullScreenWrapper.js, adblock.js, theme.js
Custom apps: marketplace, lyrics-plus, eternal-jukebox, spicetify-stats-dist

**Comment by harbassan** [comment] 2023-05-04 03:14
can you show me the console by opening devtools

**Comment by tegraion** [comment] 2023-05-04 18:28
![image](https://user-images.githubusercontent.com/119058830/236295800-7a6bbb49-458e-4101-b0d2-67c64044ad7d.png)

**Comment by tegraion** [comment] 2023-05-04 18:29
![image](https://user-images.githubusercontent.com/119058830/236296069-b9043806-da6a-434f-85b4-80b75d2deca0.png)

Sorry about that. This is my first time using github.

**Comment by harbassan** [comment] 2023-05-04 19:54
do you have any sort of special track in any of your playlists that isn't a normal song?

**Comment by tegraion** [comment] 2023-05-05 10:09
What do you mean? What kind of song?
My library has about 3500 liked songs and more than 100 playlists (each has 100-200 songs in them), some I made, some I follow from Spotify or other users. But can't think of any track that isn't a normal song.

**Comment by harbassan** [comment] 2023-05-08 08:09
As of the moment I don't know why the issue is happening but I suspect its because of the amount of songs you have in your library. Ill try and fix this soon.

**Comment by Cry4775** [comment] 2023-05-24 17:41
I have the exact same issue and I have lots of songs and playlists in my library too, so I guess it's the amount of songs.

**Comment by RetardedNConfused** [comment] 2023-05-25 10:49
:(

**Comment by harbassan** [comment] 2023-05-25 10:52
@Cry4775 How many songs do you think you have exactly? could you do an estimate?

**Comment by Cry4775** [comment] 2023-05-25 11:09
~3000 liked songs and ~100/150 playlists

**Comment by harbassan** [comment] 2023-05-25 11:13
oh wow, that must be the reason then, I'll try and find a fix for this, would probably involve waiting a while for everything to be fetched but atleast it would work.

**Comment by ApothisXD** [comment] 2023-05-31 12:15
I'm having the same problem as the rest 
My liked count being 3,495 songs
😔

**Comment by harbassan** [comment] 2023-06-05 00:14
try installing the latest release that I just made and see if that fixes anything. It might not, but since I cant replicate the issue its difficult to fix.

**Comment by Cry4775** [comment] 2023-06-05 18:08
still broken unfortunately

**Comment by harbassan** [comment] 2023-06-06 00:04
ok then can you send a ss of the devtools, i just updated the error logging so it should be clearer where the issue happened. send the ss of what happens after you click into the library page after a good few seconds and you can see an error relating to stats.

**Comment by sian57** [comment] 2023-06-06 00:05
not sure if it's any help but it's also stuck for me but I only have like 100 liked songs and 10 playlists which is significantly less than other people :)

**Comment by harbassan** [comment] 2023-06-06 00:13
yep definitely helps, now I know that the problem isn't actually related to the length but something else that's in the playlists themselves. Can you think of anything in your playlists that isn't a normal song/track. also could you try and show the error In the console

**Comment by sian57** [comment] 2023-06-06 00:18
yea i defo have some songs in a playlist that isn't from spotify - songs downloaded from youtube than put into itunes then onto spotify somehow, cant really remember exactly how tbh.
also extremely new and not sure how to show the error, will do if someone can explain sorry!

**Comment by harbassan** [comment] 2023-06-06 00:29
in the cmd line type spicetify enable-devtools, then once spotify opens you should be able to right click on an empty part of the page and select inspect element. From there go into the console tab. Then go into the stats library page and you should see an error eventually come up, should have something to with stats in the error. Just send a ss of that.

**Comment by sian57** [comment] 2023-06-06 00:33
![Screenshot (36)](https://github.com/harbassan/spicetify-stats/assets/135673036/4eca4c56-e503-43e3-a040-0d8db0b9e996)
![Screenshot (37)](https://github.com/harbassan/spicetify-stats/assets/135673036/5e02339b-05cd-4878-9bec-d72e42acc9de)
![Screenshot (38)](https://github.com/harbassan/spicetify-stats/assets/135673036/12230e47-0ad9-4cb8-997f-8bca3fb081da)
![Screenshot (35)](https://github.com/harbassan/spicetify-stats/assets/135673036/d9ce1bd8-f9f2-4b1c-99e7-d41988743b45)
okay loads came up so i screenshotted it all just in case, hope it helps! :)

**Comment by Cry4775** [comment] 2023-06-06 08:49
These are my logs instead

![Schermata del 2023-06-06 10-47-05](https://github.com/harbassan/spicetify-stats/assets/63257144/62d7ae5e-63f0-4954-a41d-38c12f83eb01)
![Schermata del 2023-06-06 10-47-20](https://github.com/harbassan/spicetify-stats/assets/63257144/af73dfba-15ee-4258-9474-fcf056b8d113)
![Schermata del 2023-06-06 10-47-30](https://github.com/harbassan/spicetify-stats/assets/63257144/9bf1810a-cddd-42d2-b899-62e5c6182c3d)
![Schermata del 2023-06-06 10-47-52](https://github.com/harbassan/spicetify-stats/assets/63257144/79e90113-3785-4ff3-882d-7dfd645e5372)

**Comment by harbassan** [comment] 2023-06-06 09:01
yeah from what I can see atleast 3 of your songs have something wierd going on with them, could you try and copy the url of the failed requests. Like the whole url which is quite long, and then just paste it here.

**Comment by Cry4775** [comment] 2023-06-06 09:11
https://api.spotify.com/v1/audio-features?ids=1brwdYwjltrJo7WHpIvbYt,0mHmIiOqGhAttmJALd2MuW,6Ep6BzIOB9tz3P4sWqiiAB,2Oehrcv4Kov0SuIgWyQY9e,4eLSCSELtKxZwXnFbNLXT5,0RchWnEHETINMAyrTrlBmo,6VRghJeP6I0w1KxkdWFfIh,2Heh0PiDG6F9fUHID8XV0Z,4uyDe8SeM0Nsgzp9KMtXWn,0fImO9nxvrFnVRpp4COwkS,3MJKxSSaKypYBEiXEXPPoR,3jRQmxNh59Rfsi0TrXlcme,6SCDzH7OCgpzwCP8yo7HIP,4vPj476CryAhNwhn7fCaQa,4IWAyPf1KMq7JCyGeCjTeH,4dASQiO1Eoo3RJvt74FtXB,6jmngk8Fwup05JZ6kgXEGX,0tKcYR2II1VCQWT79i5NrW,7vAXN57IQ0sj049wZGIboE,3IuPHUeLhSfuzSQ4AZTAIM,4jqfnEuLSF7ilmtQVvrW7G,16BwgbCMbiwREPTS46QNKr,1brwdYwjltrJo7WHpIvbYt,3eCRC69Xnq9yVj6Wx2Zkv9,33bhupOJQbOCM1VwjXQrIg,1zkAG9dMjkymWozuWuYNOF,4qCfSgJjkU9FZD3DSKvsH3,6WeMckuqw38OVkVYxFOW2m,1rbDgYU4In8OvJHAgE3lXu,3eCRC69Xnq9yVj6Wx2Zkv9,0EWJ9yjut9XVdogneOSXJz,5uQUEdKcdgHO61CBmynHFI,4V0cZimG1H3Hswu9BE8NgC,5sZjeBYYeVBXDCy5ox1JhS,5qVwiIw05xLv3IwTtqdd5S,16BwgbCMbiwREPTS46QNKr,6ylJlLyBdzZQMO3iR1GlIV,6v2NDXnU09gdZaMwsC9fGo,17y9hYNYqeJhaV1AoeDxxJ,0enu2s0XtU2BAKJZfJApVM,6c2plQ4ltMJ8LHRayGs2xR,3TCAhSROdF6EV01czl2Zhp,1lGZ4rEgUHclwnH1F507pz,06J1AJ99IfAOqzgLkkY76A,4NISh0Q28phSa4k74F7mV6,7L674A0bhxm6ksZK1FSonY,3bK7VNOEQHX7ctTVx1vOiO,4BTcih8EZMYMn0LxEsq0hX,48eD9MeqQHJDRK1m7mIqUU,,4nkBL9MVNCSfUJpNHKeiyb,08z6EsebfUH0Q6J0Wf3eWf,7ASwz1NnssLo0uOw7e4LqO,73zMtxGIBJ0uwv4L830V9u,Melanie+Martinez,3kL30Pjp90WKuX89Fx5TOv,4BTcih8EZMYMn0LxEsq0hX,569FIyqPyduePIQ8yL9uAU,2zyqX8K1twx0sW2UOiioC1,3YnZjZgwFapSw7J9FPlhpf,267iugrEOSP3031PKC7KXE,4dH9b0nxd9lLlfH1rW8MZN,66hzBMX46t2WvO4HH7kgiU,2yfmtCf7UrnamrER2QzPPN,6iD0QDmfpCvsQGwTZVcE3c,3qKGvSu1inEZKwYQnMavNA,12yGwtB2h9NlzeOKYfVYTF,0QCoA8f4gK0lGtGzCIrBjg,6YtsE7s0IU3ipwE3Np1iHw,14eqkkICgX9BTqL8qykxJ7,3pR8LVnJrvXwxs2rmMbwks,23EDf0JoMkm4q02guk2DJl,4HEFKRGM0Z3c24PtBkUYtc,4DErCvO9irCDFmNZWnNw3E,7xkQdy0cy5ymoWT7nedvLz,0yp6ui2sosUjCUro1rRk2Q,0q3xdwnXoHgHsc32CxpTG4,05V2NyH94UEcJLNgZDAkvv,5jwiiUlbP6THaA89zDM3i0,5rcM6AQTNhRRXLlANbYP2T,,GTA+%2C+Aero+Chord,,,19916uKFpyBCtTzaMoJwv1,2R5hVuEMowwD8LIIy15vCM,4yNoaxUJjnP50AXYoAZx4S,2wzPSYbxGhEJzd6BSxskU3,38Zku0N2KqfHRe18ErpKGC,05eopGTXIpcaDMgwPN1ViO,4uaKkokxOTir1EC20LngSV,,32RWuw9Ie9NjfxPURIIEzK,3s5mjNVrSstGMcDMwD1q91,7zrok5I7I7AHlSiShMDx3Z,66lUXEYaT77Z90weKu8X9Z,3k4AW2gDUlzfShVCTjK9EI,0SwNZINSaXhZ2KwbvxUCyx,5cZTbDkB2iJslDNr7SGkiQ,5AozIHwb7H24xf8iuSwJSk

**Comment by harbassan** [comment] 2023-06-06 11:12
oh right yeah that makes sense, I can see some of the songs have either weird ids or just no id at all, which is probably affecting the artists metadata as well actually. Ill let you know when I do the fix so that you can test it.

**Comment by ApothisXD** [comment] 2023-06-06 23:35
Could removed songs still in my liked and playlists affect it?

**Comment by ApothisXD** [comment] 2023-06-06 23:36
![image](https://github.com/harbassan/spicetify-stats/assets/133063330/0338388f-1ca2-4d13-b555-915d7f9fbb90)

like this one

**Comment by harbassan** [comment] 2023-06-06 23:37
yep probably

**Comment by harbassan** [comment] 2023-06-09 12:27
@Cry4775 @ApothisXD @sian57 could you all try out the updated code in the dist branch, im hoping itll fix the issue. If you're still getting an error, let me know.

**Comment by Cry4775** [comment] 2023-06-09 13:09
It's kinda strange but last time I deleted 2 out of 3 playlists that were causing the issues, also to clean up my library from old playlists, and yesterday I randomly noticed that statistics are now working, even though I left one of the playlists that were causing the issue, in fact on console it still prints the errors about that playlist. 
I tried replicating the issue again, but I couldn't, I also tried the new version to see if the errors in console were still printing at least and yes, nothing changed there.
I have no idea how it happened, but I feel like it's loading up some kind of cache too, because if I like a song and add it to library and playlists, the library screen doesn't change, the counter doesn't go up even if I refresh (idk if I'm doing something wrong). Odd things happen :(

**Comment by Cry4775** [comment] 2023-06-09 13:41
https://api.spotify.com/v1/audio-features?ids=0Njuk9ivU3IwFfx9sxuwuh,1MKfplOg9xC8EIzL9nMBWi,77QKhqcmYh04hBnLZljk27,3mof6Z6vz6gonsuIEQXank,1FJdcvpJVfrGSIltpgltDd,0cgRDeRDPNrfRifO8WHit8,2GemKcAkxOA9OrGBhCo1jR,3cz4pIcDCo64tcE0jh9xkZ,2m8GfSKLEKgxnQ8IatGeam,7fZmfciYc0EZA1dJjA87sT,02Yq8TMuecXONAjkORNJNM,06Z4KrQAiE8hQBOdwBuG0j,6dNLZg4ZgIw4ESV7ul2NpY,4QUrmlkODWlF5wZT7hPwlH,4fb0iBhHbQeiJHOfLr6R75,6sjtHq6EueMR7otphregK5,5SFK7qsG5U34HbFxkmHW7e,2wINoRCKEZtA4CuLLwP86J,30y26KfyDlsSbslOg9SC2q,7ImGFwpCuTLxsK9QvfMwcX,7BC3xtQZuwOMDSdpE8Qn3P,19ZUE3GvgEOB1INnUEZOzd,0ILxg725sebcR1w1IjI85I,7ftTq0hWv6qZ9ITuthc7Wt,4aJnMRNeuDZSQN7FaSNGtM,69d67l28GKygFwW4QbyfDR,4wCNDV8vhPo3MkWnN5ccUK,2Tl0tgMlLnG921VEf9Ufut,6bdKfvAxiQx8J2KgOjjCGE,098Krv08Lj9YlZShuq5564,3nKx86fcs8MYMydill0Sya,0cQTTt9W487gf2kzfUumTM,34jwwarSH193WBWeXyEI31,0x3EdJ365doyy9T2dd4g6Y,66WcaWVGRFmpx0euxmw9yM,0E1RL6rKe18aUq70B2fgXs,16BwgbCMbiwREPTS46QNKr,4yMUywwLJwsWd1v9zow2MH,2p9q7lIzhJygg323PqeMbD,3HrvOaJJfVfe3C2TboSh7Y,73zMtxGIBJ0uwv4L830V9u,5JI4Hz1uoNbr1n6vzed64T,5rAZJ4K9K0U4BVE6mJBZbW,1CRESO4AuKm5B5Lqodk7t9,27Uz9gSMNzDRhwtgUvy5V8,3uYOtfzyQr7zXBxNeXovMl,26yGxHiLkXJkQ7FsmTGfod,0hqAWKZDhuOfFb6aK002Ph,50ciUo89kUtN2CJoyeYBPK,4XvCi9ugjgRn4Etwe0KaVI,1CqOoPwOBBxAOIrGebTe3u,7JulvZ6FrQwuyZlxdAiXgr,3eu4bRLCHovbj9zmlE9Svl,4WhJIrDvdLE8BzD1cY3gFC,2WWyllDdKzdgcj7SlT7pt7,5Ij5AACeUzstvpgEPUEQW1,5tZ7rr2pkCqB2MRR5YPsU3,5Du9saCXYuRkHcj3CA6Her,0Gb8ICL5WXAZjcP7VSb9G6,6uzNlE36xl1kpVFfvxpd7v,7zCxnbrTrWMBPOYlTQXAfC,0teG1tVhtrFoIJrTConkuy,3eUBCaLMh0jYVmeZAQnm46,2p9q7lIzhJygg323PqeMbD,1kZtKMeWgKEsRJBHHVup2a,1AxVhl7hQPEmUBRyFQk1Le,1mGZj8TJeTeIWuc8EQK9n5,5nJvN4zWxlEVeNEVovgIuA,61uOSqcShc3TzIlnCurRtz,2SsKj9v9mg0fs3YesH5pkj,1ArfTWwebrzXFvxzlXnFKV,4bOBkYCCIIIp32uQYtRtAR,0QCoA8f4gK0lGtGzCIrBjg,0niB1XqRCw80iWppaAQiEP,5ERWSokrBWx8sUwHV6QN93,66WcaWVGRFmpx0euxmw9yM,05eopGTXIpcaDMgwPN1ViO,4Pngbdh5TjyXa3hOjuDgGE,4XB0xu7PoC5rj8YpHzvo3y,2tY2EdWx0ofDN2h1nldpkz,65ngBEfh5u1B9zbzQN6CQB,6i30DSKZvkxCz2uxqWPhKI,0MsDvKdrvaw1zuk9ew5Ioy,30Fpc4IW7sQFzYJWImWRst,2TsMgZTaacXikcOAEezzyk,1cGqqROuQQGQ2VF2tBihYv,5Tga2UBWNq8YIfh7yiSenY,7Gcs2GtX03rcUps8XAUpMA,0a3C5qrU3jEn00RfjVW3Ep,0E1RL6rKe18aUq70B2fgXs,16BwgbCMbiwREPTS46QNKr,4yMUywwLJwsWd1v9zow2MH,0PZOWtW7Hg8gEhXcQaHXlY,3HrvOaJJfVfe3C2TboSh7Y,The+Two+Friends%2C+Jeff+Sontag%2C+Culture+Code,,,Tristam+%26+Stephen+Walking,Tristam,4QTes6BvO9Ce0jW3qIrAyK

Here's the URL of the error currently.

**Comment by harbassan** [comment] 2023-06-09 14:08
oh right yeah I'm an idiot and made a silly mistake, so the filter didnt actually apply. I'll update it in the morning

**Comment by harbassan** [comment] 2023-06-09 23:46
ok try it now, hopefully this finally fixes it

**Comment by ApothisXD** [comment] 2023-06-10 00:44
still not working

**Comment by harbassan** [comment] 2023-06-10 02:55
your error must've been a different one then, could you show your logs?

**Comment by ApothisXD** [comment] 2023-06-10 03:21
Yeah sure, gimme a sec

**Comment by ApothisXD** [comment] 2023-06-10 03:23
![image](https://github.com/harbassan/spicetify-stats/assets/133063330/c2b7d8f6-28db-483b-8590-13bb306142a5)

**Comment by ApothisXD** [comment] 2023-06-10 03:23
![image](https://github.com/harbassan/spicetify-stats/assets/133063330/c5818005-f52a-4cbb-936e-a5caa39dc1dd)

**Comment by ApothisXD** [comment] 2023-06-10 03:24
there ya go

**Comment by Cry4775** [comment] 2023-06-10 09:45
Now it works perfectly for me!

**Comment by harbassan** [comment] 2023-06-10 10:21
@ApothisXD you've still got the older code installed, could you try reinstalling it with the link in the README.

**Comment by ApothisXD** [comment] 2023-06-10 13:29
Ight will do

**Comment by ApothisXD** [comment] 2023-06-10 13:37
![image](https://github.com/harbassan/spicetify-stats/assets/133063330/dfa5d803-5e44-4d01-a2af-1f7afe6a1119)

**Comment by tegraion** [comment] 2023-06-10 16:31
![image](https://github.com/harbassan/spicetify-stats/assets/119058830/4b42dd02-e2fb-412b-ae68-a311e12de664)

Thanks @harbassan it's working for me too.

**Comment by sian57** [comment] 2023-06-10 20:02
> @Cry4775 @ApothisXD @sian57 could you all try out the updated code in the dist branch, im hoping itll fix the issue. If you're still getting an error, let me know.

sorry completely forgot about this forum, is there anything you needed to me to try sorry?

**Comment by harbassan** [comment] 2023-06-10 23:35
Just update and it should work

**Comment by harbassan** [comment] 2023-06-10 23:36
> ![image](https://user-images.githubusercontent.com/133063330/244873853-dfa5d803-5e44-4d01-a2af-1f7afe6a1119.png)

lol the percentages are totally messed up, def need to fix that

**Closed** 2023-06-12 11:44 UTC
