### ISSUE TITLE
I tried to update stats

### ISSUE THREAD

**Issue by ADaga460** [harbassan/spicetify-stats#40] opened 2023-11-11 20:45 UTC
I tried to integrate both new folders and added into spicetify, but it refuses to load. Either make it one single folder or make the new installation process easier and write it down so we know how to do it rather than fumbling around

**Comment by harbassan** [comment] 2023-11-11 22:16
It's the same process. Theres only one folder that you need to put into the custom apps folder, which is the 'stats' one. 

What part of the readme do you think is confusing, so I can fix it.

**Comment by ADaga460** [comment] 2023-11-12 02:22
sorry i'm a bit of an idiot bear with me here
there are two files we need to download new: both have a manifest.json
do we just put the "extension.js", "index.js", and "style.css" and leave out manifest.json into the folder called spicetify-stats-main? or do we replace spicetify-stats-main's manifest.json?
what files should go into the folder that we rename to stats? i think the most confusing parts is the duplicate "manifest.json".

**Comment by harbassan** [comment] 2023-11-12 04:27
There should only be one file you need to download, the spicetify stats zip file. just unpack that and put the contents into the stats folder, replacing all the old files. basically the only 4 files you need are the style, extension, index and manifest, which are only in that zip.

**Comment by ADaga460** [comment] 2023-11-12 08:48
Still doesn't work. Could you just put all the files we need for the new stats into one folder that we rename to stats and put it into spicetify? seems less clunky than having to replace old files

**Comment by harbassan** [comment] 2023-11-12 08:51
Thats what ive been trying to say. All you need to do is download the zip file, unzip it and rename it to stats, and put it in the custom apps folder.

**Comment by ADaga460** [comment] 2023-11-12 09:30
Dude it still gives the error that "Something is wrong". Maybe incompatible version of spotify? Can you just send the file that I need to download, because I've tried downloading everything here and all of them give the same error.

**Comment by Hrushal-Nikhare** [comment] 2023-11-12 10:21
Same issue. i just upgraded

**Comment by Hrushal-Nikhare** [comment] 2023-11-12 10:22
also once you click on stats you have to reload to make everything normal

**Comment by Daniverzum** [comment] 2023-11-12 10:25
for me it worked for a bit, it only started giving the "Something went wrong Try reloading the page RELOAD PAGE" after I went to the library page in the Statistics menu, but now it it defaults to that even if I try to reinstall it and the stats app doesn't work at all

**Comment by Daniverzum** [comment] 2023-11-12 10:29
Also, this is a duplicate of #39 , but if you already had the Library selected you can't tell whether the whole app is broken or just because of the Library page

**Comment by harbassan** [comment] 2023-11-12 10:32
Could someone screenshot the error logs, obviously something is broken but I have no clue what it could be.

**Comment by Hrushal-Nikhare** [comment] 2023-11-12 10:41
can you guide me on how to do that?

**Comment by Daniverzum** [comment] 2023-11-12 11:00
![image](https://github.com/harbassan/spicetify-stats/assets/15160989/1486239e-6003-4221-a017-5a5c85b7bca7)
![image](https://github.com/harbassan/spicetify-stats/assets/15160989/574f2f6e-20d2-455c-b4af-1632d7be793a)
![image](https://github.com/harbassan/spicetify-stats/assets/15160989/ff63264d-7424-42cd-a4ab-b1d6bd03dda1)

**Comment by harbassan** [comment] 2023-11-12 11:03
thanks, ill fix this soon. For now use the previous version which should be working fine.

**Comment by Hrushal-Nikhare** [comment] 2023-11-12 11:04
tested: https://github.com/harbassan/spicetify-stats/tree/c0e8668a742edc47622cc6fb40cca0ff54bd0554 its working rn

**Comment by Hrushal-Nikhare** [comment] 2023-11-12 11:04
download the code as a zip file and replace the files

**Comment by harbassan** [comment] 2023-11-12 11:10
yep i've reverted it so you can just use the readme link or the version 0.1.0 release file.

**Comment by ADaga460** [comment] 2023-11-12 18:40
really strange how its causing a "reload page" error, the new feature seems so cool too
0.10 does work though
<img width="465" alt="Screenshot 2023-11-12 at 10 40 30 AM" src="https://github.com/harbassan/spicetify-stats/assets/104458359/37453799-30c8-4d27-a9ef-a28ad8a8e9fc">
I think the fact that it doesn't have an index.js, extension.js, and style.css may be a problem

**Comment by harbassan** [comment] 2023-11-13 05:56
Can one of you check if its fixed by downloading the files in https://github.com/harbassan/spicetify-stats/tree/v0.2.0-dist?

**Comment by ADaga460** [comment] 2023-11-13 06:13
Looking good! I do have two questions:
1. There seems to be a "playlist stats" feature, but that doesn't appear (as in individual playlist stats)
2. Stats icon doesn't show up, weirdly
<img width="279" alt="Screenshot 2023-11-12 at 10 14 38 PM" src="https://github.com/harbassan/spicetify-stats/assets/104458359/061886c4-f2e7-41be-b4fc-e032746db93b">

**Comment by harbassan** [comment] 2023-11-13 06:15
Could you screenshot your stats folder for me, seems to be something wrong with it

**Comment by ADaga460** [comment] 2023-11-13 06:16
<img width="484" alt="Screenshot 2023-11-12 at 10 18 18 PM" src="https://github.com/harbassan/spicetify-stats/assets/104458359/2fefd3d7-1284-40b7-9ce9-6a149777788d">

**Comment by harbassan** [comment] 2023-11-13 06:18
yep ok when you download and unzip the folder, just replace the whole folder, because some of those shouldnt be there

**Comment by ADaga460** [comment] 2023-11-13 06:20
works now, thanks bro clean update

**Comment by ADaga460** [comment] 2023-11-13 06:21
although I still wonder why the individual playlist stats isn't working?

**Comment by harbassan** [comment] 2023-11-13 06:21
would be a button like this: 
![image](https://github.com/harbassan/spicetify-stats/assets/84175605/280ce4e6-ab8c-4b51-96de-9a903b386060)
click that on a playlist

**Comment by ADaga460** [comment] 2023-11-13 06:22
OH i see it! niceeee

**Closed** 2023-11-13 06:34 UTC
